name: CI & CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # ⇣ 1) 產生全小寫的映像與快取路徑
    - name: Prepare lowercase image names
      id: prep
      run: |
        IMAGE=ghcr.io/${GITHUB_REPOSITORY,,}:latest   # toLower
        CACHE=ghcr.io/${GITHUB_REPOSITORY,,}:cache
        echo "image=${IMAGE}" >>"$GITHUB_OUTPUT"
        echo "cache=${CACHE}" >>"$GITHUB_OUTPUT"

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.hmlss_cyc_pat }}

    # ⇣ 2) 使用剛剛產生的小寫變數
    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.prep.outputs.image }}
        cache-from: type=registry,ref=${{ steps.prep.outputs.cache }}
        cache-to: type=inline
