name: CI & CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    # ⇣ 新增這個 step，產生全小寫的 IMAGE_TAG ⇣
    - name: Prepare lowercase image tag
      id: prep
      run: |
        IMAGE_TAG="ghcr.io/${GITHUB_REPOSITORY,,}:latest"   # bash 展開 ,, = toLower
        echo "image=${IMAGE_TAG}" >>"$GITHUB_OUTPUT"

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ㄘㄩhmlss_cyc_pat }}

    - name: Build and Push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ steps.prep.outputs.image }}
        cache-from: type=registry,ref=${{ steps.prep.outputs.image }}-cache
        cache-to: type=inline
